services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=media-app
    volumes:
      - ./postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:media-app@postgres:5432/postgres?connect_timeout=300

networks:
  default:
    name: nginx
    external: true
